name: Update GitHub Stats

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'  # каждые 6 часов

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python github_stats.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "egor-bot"
          git config user.email "bot@egor.dev"

          git add README.md
          git commit -m "🔄 update stats" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

          
